### PR TITLE
bugfix for prepare_librispeech command

### PR DESCRIPTION
**Pull request by rosrad**
bugfix for prepare_librispeech command when the default dataset_parts=auto is used.

bug:
command below will not correctly prepare the manifest of librispeech
lhotse prepare librispeech data/LibriSpeech data/manifests

### CODE REVIEW

**Comment by pzelasko** [comment]
Thanks! Can you fix the linter errors?

**Comment by rosrad** [comment]
Tried to fix the errors from black. By the way, do we have some configure for the black and flack check here ?

**Comment by csukuangfj** [comment]
> Tried to fix the errors from black. By the way, do we have some configure for the black and flack check here ?

I think it exists only in the CI, see
- https://github.com/lhotse-speech/lhotse/blob/master/.github/workflows/flake8.yml
- https://github.com/lhotse-speech/lhotse/blob/master/.github/workflows/black.yml

I would recommend adding something like what we're doing in icefall, e.g., https://github.com/k2-fsa/icefall/blob/master/.pre-commit-config.yaml
See also https://icefall.readthedocs.io/en/latest/contributing/code-style.html

**Comment by rosrad** [comment]
@csukuangfj thanks for the inform. it is good to have this pre-commit check. 
I found that in this repo there are different line-length check from black(80) and flake8(127).  @pzelasko  do you think we should align this line-length to be 80 in both black and flake8. And I think we should add pre-commit check as well so that beginner will get the lint error earlier than the PR merge.

**Comment by pzelasko** [comment]
> @csukuangfj thanks for the inform. it is good to have this pre-commit check.
> I found that in this repo there are different line-length check from black(80) and flake8(127). @pzelasko do you think we should align this line-length to be 80 in both black and flake8. And I think we should add pre-commit check as well so that beginner will get the lint error earlier than the PR merge.

Thanks, I think it's a good idea, but I might not have the time to add it right now. Would you be interested in contributing this?

**Pull request merged**
