### PR TITLE
Add tolerance to validate_recordings_and_supervisions (#205)

### PR DESCRIPTION
**Pull request by janvainer**
Discussion is here: #205

### CODE REVIEW

**Comment by danpovey** [comment]
Guys, 
my wife Nadira was getting a problem with

ValueError: Cannot load features for recording None starting from 1003.52s. The available range is (1003.52001953125, 1021.28001953125) seconds.

presumably from this line:  https://github.com/lhotse-speech/lhotse/blob/c1d443288373ceaf50aee665a9bc9831a82356a4/lhotse/features/base.py#L475

... I'm not 100% sure of the workflow she was doing & where she got this manifest, but do you have any idea what is the recommended fix at this point?

Screen Shot 2024-06-02 at 11 06 12 PM

**Comment by pzelasko** [comment]
That's weird, the diff is less than the duration of a single sample for 16kHz. But anyway that tolerance seems too tight for features, we should probably change it to sth like 1e-3 to avoid these issues.

**Comment by pzelasko** [comment]
Try with this PR https://github.com/lhotse-speech/lhotse/pull/1349

Another possible workaround is to manually fix the manifest updating feature.start = cut.start

**Comment by npovey** [comment]
In the example above I was just running libriheavy script on "medium" subset.  

PR #1349 fixed my problem. 
thanks

**Pull request merged**
