### PR TITLE
Allow extend_by to pad arrays and features

### PR DESCRIPTION
**Pull request by pzelasko**
@desh2608 could you please review this change as you're well familiar with this code? The main point is to allow padding other fields than `recording` when using `extend_by` rather than just discarding the data.

### CODE REVIEW

**Review by desh2608 — APPROVED** [review]
LGTM.

Regarding the `pad_feat_value`, I was wondering if a more scalable approach would be for the `Features` class to have a `default_pad_value` property which is defined for each feature (for example, it may be log epsilon for logarithmic features or epsilon for STFT features, etc.). We can then use this default value for padding purposes instead of having users manually specify it. I faced some issues related to this recently when mixing STFT features.

**Comment by pzelasko** [comment]
> Regarding the `pad_feat_value`, I was wondering if a more scalable approach would be for the `Features` class to have a `default_pad_value` property which is defined for each feature (for example, it may be log epsilon for logarithmic features or epsilon for STFT features, etc.). We can then use this default value for padding purposes instead of having users manually specify it. I faced some issues related to this recently when mixing STFT features.

I agree, but the implementation should be backward compatible (i.e. allow to correctly read manifests before this change).

**Comment by desh2608** [comment]
> > Regarding the `pad_feat_value`, I was wondering if a more scalable approach would be for the `Features` class to have a `default_pad_value` property which is defined for each feature (for example, it may be log epsilon for logarithmic features or epsilon for STFT features, etc.). We can then use this default value for padding purposes instead of having users manually specify it. I faced some issues related to this recently when mixing STFT features.
> 
> I agree, but the implementation should be backward compatible (i.e. allow to correctly read manifests before this change).

I think that should be doable. I'll make a PR later.

**Comment by pzelasko** [comment]
You know what, I will close this one for now. There is an edge case of:

```
|-------recording-------|
  |----features---|
  |-----cut-------|
 |---extended-cut---|
```

with `pad_silence=False` where we don't want to pad so we'd have to discard or raise error, and I don't really need these changes right now on a second thought. We can revisit if it's needed...

**Pull request closed without merging**
