### PR TITLE
Sampler diagnostics updates: preserved across epochs, fixes for various samplers, extended unit tests

### PR DESCRIPTION
**Pull request by pzelasko**
CC @csukuangfj @danpovey , I think it addresses all of the issues you raised recently. Please give it a try and let me know.

### CODE REVIEW

**Comment by csukuangfj** [comment]
It throws the following exception for this PR when using the master branch of icefall:
```
2022-03-24 11:12:41,413 INFO [asr_datamodule.py:301] Loading sampler state dict
Traceback (most recent call last):
  File "./pruned_transducer_stateless/train.py", line 934, in <module>
    main()
  File "./pruned_transducer_stateless/train.py", line 927, in main
    run(rank=0, world_size=1, args=args)
  File "./pruned_transducer_stateless/train.py", line 818, in run
    train_dl = librispeech.train_dataloaders(
  File "/ceph-fj/fangjun/open-source-2/icefall-master/egs/librispeech/ASR/pruned_transducer_stateless/asr_datamodule.py", line 302, in train_dataloaders
    train_sampler.load_state_dict(sampler_state_dict)
  File "/ceph-fj/fangjun/open-source-2/lhotse-master/lhotse/dataset/sampling/bucketing.py", line 271, in load_state_dict
    sampler.load_state_dict(sampler_sd)
  File "/ceph-fj/fangjun/open-source-2/lhotse-master/lhotse/dataset/sampling/simple.py", line 167, in load_state_dict
    self.data_source.fast_forward(self.diagnostics.total_cuts)
  File "/ceph-fj/fangjun/open-source-2/lhotse-master/lhotse/dataset/sampling/data_source.py", line 82, in fast_forward
    next(self)
  File "/ceph-fj/fangjun/open-source-2/lhotse-master/lhotse/dataset/sampling/data_source.py", line 93, in __next__
    next_cut = next(self._iter)
StopIteration
```

**Comment by pzelasko** [comment]
I think I know what happened. I’ll try to fix it tomorrow.

**Comment by pzelasko** [comment]
I think it should work now, but you'll have to test it with fresh sampler checkpoints as their structure had to change.

**Comment by pzelasko** [comment]
I'm merging as it seems to be working to me after extending unit tests; if you still encounter issues LMK and we'll follow up.

**Pull request merged**
