### PR TITLE
Validation methods for various Lhotse manifests

### LINKED ISSUE #13: Validate manifest
We could use a python function `validate_manifest` and a corresponding CLI mode `lhotse validate` at some point to check data integrity (like Kaldi `validate_data_dir.sh`).

### PR DESCRIPTION
**Pull request by pzelasko**
It's conceptually similar to Kaldi's `validate_data_dir.sh`, but probably performs different checks.

I haven't tested it yet, just pushing the code written so far.

Resolves #13

### CODE REVIEW

**Comment by danpovey** [comment]
Cool..
How can we ensure that this actually gets used?
In Kaldi you follow the recipes and they call the validation, not sure if there is an exact analogue here unless we call it whenever we write something to disk, or read from disk (by default), or something like that.

**Comment by pzelasko** [comment]
We can add them to all prepare_corpus functions, and use them in snowfall recipes too, which is probably the closest analogue to Kaldi. Do you think that’s enough?

**Comment by danpovey** [comment]
sure, that sounds OK

**Comment by pzelasko** [comment]
I extended the validation to check recording <-> supervision consistency, and added that to each corpus prep method. 

I suppose it could break some of the corpus data prep scripts if they did not have rigorous checks before. I'll check some of them (so far LibriSpeech is OK) and then merge. If anybody in the community wants to check a corpus they are using with these changes, let me know (I'll probably merge this in 1-2 days).

**Comment by pzelasko** [comment]
BTW after merging this PR, likely all CutSet's will have to be re-created (I found and fixed a bug in supervision <-> cut channel consistency and supervision <-> recording ID consistency after speed perturbation).

**Comment by pzelasko** [comment]
I'm merging, if there are any issues with the recipes we can resolve them later.

**Pull request merged**
