### PR TITLE
Build recipe for TAL CSASR dataset (a multilingual dataset)

### PR DESCRIPTION
**Pull request by luomingshuang**
In this PR, I build a recipe for TAL CSASR dataset which is a multilingual (Mandarin and English) dataset. It runs OK. I set the language as `English-Chinese` in the supervisionset. I notice there is an existing PR #738 referring to it.

### CODE REVIEW

**Comment by pzelasko** [comment]
How should we manage the conflict? Is there a significant difference between your recipe and the one in #738? Might be easier to just merge the other PR if not.

**Comment by luomingshuang** [comment]
I try to build this recipe because I plan to build a recipe based on TAL CSASR for icefall. I have used it to generate my TAL CSASR manifests successfully. Em....before I submit this PR, I don't notice the #738. One difference between this PR and #738 is that I set a progress bar for preparing each dataset part. I think it's good for spying the process. I'm OK if you think the PR can be merged into #738.

**Comment by luomingshuang** [comment]
The progress bar shows as the following picture:
image

**Comment by pzelasko** [comment]
If it's all the same to you, I think it'd be easier to merge #738 once all comments are resolved.

**Comment by luomingshuang** [comment]
OK， and I will close this PR.

**Pull request closed without merging**
