### PR TITLE
Fix and enhance TIMIT recipe

### PR DESCRIPTION
**Pull request by flyingleafe**
- [x] Actually touch `.completed` detector file to avoid re-downloading
- [x] Actually use multiple processes during preparation when `num_jobs > 1`
- [x] Fix the paths to audio files and transcriptions in the unpacked folder (add `data` subdirectory)
- [x] Use full text as transcription on `SupervisionSegment` level; add word and phoneme transcriptions as alignment layers.
- [x] Provide info about speaker's gender explicitly to `SupervisionSegment`
- [x] Better progress reporting via tqdm

### CODE REVIEW

**Comment by pzelasko** [comment]
@luomingshuang could you take a look? I think you were building the Icefall recipe for TIMIT, would be great if you checked this PR doesn't break it.

**Comment by luomingshuang** [comment]
Ok, I will have a check for it.

**Comment by flyingleafe** [comment]
@luomingshuang bump, all good?

**Comment by luomingshuang** [comment]
I am having a check for it.

**Comment by luomingshuang** [comment]
Well, I think this PR is ready to MERGE. It adds some functions for alignment.

**Review by pzelasko — APPROVED** [review]
Thanks for the contribution @flyingleafe and for the help in reviewing @luomingshuang!

**Pull request merged**
