### PR TITLE
Add support for supervision segments in SpecAugment

### PR DESCRIPTION
**Pull request by pzelasko**
In this PR, SpecAugment has an additional input of supervision segments in the same format as K2's DenseFsaVec. This solves the issue #271 where spec-augmented features go out of supervision segments, by applying spec augment to slices of the feature matrices. 

I think the transformed batches are very interesting:

image

I'll see how/if it affects ASR training.

### CODE REVIEW

**Comment by danpovey** [comment]
Why is it necessary to avoid the zeroed segments crossing supervision boundaries?

**Comment by pzelasko** [comment]
It is not, but it would have further complicated the code. It’s the time stretching that needs to be done within supervisions, otherwise the features can be stretched outside their bounding boxes.

**Comment by pzelasko** [comment]
Alright, I modified it to warp in supervisions and mask everywhere. Note that masks may be applied to different examples than the time-warped ones. It is really not defined how exactly we should do it since the original paper did not consider concatenating cuts ;)  

Looks like this now:

image

**Comment by pzelasko** [comment]
It didn't affect LibriSpeech results in a significant way (4.99/10.21 [new] for 5.02/10.16 [old]) for averaged model after 6 epochs, but it seems technically correct to do it this way so I'll merge it.

**Comment by danpovey** [comment]
Great!

**Comment by pzelasko** [comment]
BTW I realized why it worked before -- since our models see all the frames outside of supervision segments, they were able to incorporate the frames that went outside of the supervisions into recognition.

**Pull request merged**
