### PR TITLE
CutSet.mix: add random_mix_offset option

### PR DESCRIPTION
**Pull request by rouseabout**
Patch attempts to address this situation: given a recording of continuous background noise spanning an hour (e.g. https://doi.org/10.5281/zenodo.2660112), and a training cutset of short clean utterances, create an augmented dataset.

Run-time performance is about the same as this:

```
noise = noise.cut_into_windows(duration=20).to_eager()
cuts = cuts.mix(noise)
```

### CODE REVIEW

**Comment by pzelasko** [comment]
Thanks, looks good to me! Can you add a test case for this option?

**Comment by rouseabout** [comment]
> Thanks, looks good to me! Can you add a test case for this option?

Shall do. Give me a ~week or so.

**Comment by rouseabout** [comment]
Changes:

* added complementary random_mix_offset option to the CutMix transform
* test cases for everything

**Review by pzelasko — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
