### PR TITLE
Added missing IHM channels

### PR DESCRIPTION
**Pull request by LasseWolter**
+ channels 0, 7, A and B are also used for IHM recordings in some meetings
+ checked all meetings for IHM channels, list should be complete now

### CODE REVIEW

**Comment by LasseWolter** [comment]
**Sidenote regarding the MIC_TO _CHANNELS mapping.**
I removed the comment regarding backing up to channel 6 because sometimes channel 6 is used for IHM recordings - not just as a backup. 

E.g.: 
Btr002.mrt:
`<Channel Name="chan6" Mic="s1" Transmission="w1" Gain="10" AudioFile="chan6.sph"/>`

Btr001.mrt:
`<Channel Name="chan6" Mic="s1" Transmission="w1" Gain="10" AudioFile="chan6.sph"/>`

where s1 is an IHM according to: https://www1.icsi.berkeley.edu/Speech/mr/icsimc_doc/naming.html
`s1 : Sony headset mic ECM-310BMP`

**Comment by desh2608** [comment]
Thanks! LGTM.

**Comment by pzelasko** [comment]
Thanks guys!

**Comment by desh2608** [comment]
I guess https://github.com/lhotse-speech/lhotse/issues/551 can be closed now :)

**Pull request merged**
