### PR TITLE
Kaldi-import: floor wav duration to milliseconds

### PR DESCRIPTION
**Pull request by vesis84**
Hello Piotr,
what would you think about these suggestions ?

- Kaldi-import: floor wav duration to milliseconds (I can reduce the comment, but it described how I got into it.)
- bugfix in 'validate_for_asr()', the Supervision start may be delayed

Best regards
Karel

### CODE REVIEW

**Review by pzelasko — APPROVED** [review]
Thanks Karel, looks good. LGTM!

**Comment by pzelasko** [comment]
I see the checks just finished, can you fix the unit tests and formatting issues?

**Comment by vesis84** [comment]
Okay, the formatting is good now. 

For the unit tests, I'll first need to learn how they work.
From the logs it seems that the tests are expecting the audio duration without the flooring to milliseconds.

I'll look into it tomorrow.
K.

**Comment by vesis84** [comment]
Hi Piotr,
the unit tests are now passing for me locally:
`1564 passed, 41 skipped, 47 xfailed, 5 xpassed, 394 warnings in 199.65s (0:03:19)`

It says I am a first-time contributor, so the workflows do not start automatically... :-)
K.

**Comment by pzelasko** [comment]
Thanks Karel!

**Pull request merged**
