### PR TITLE
Fix CutSet.compute_and_store_features support for lazy CutSets

### PR DESCRIPTION
**Pull request by pzelasko**
Resolves https://github.com/lhotse-speech/lhotse/issues/835

It should also help with https://github.com/k2-fsa/icefall/issues/608

@csukuangfj can you check it out?

### CODE REVIEW

**Comment by csukuangfj** [comment]
Thanks! I am testing it.

**Comment by csukuangfj** [comment]
@pzelasko 

It throws the following error with this PR:

Screen Shot 2022-10-10 at 10 50 20
Screen Shot 2022-10-10 at 10 50 37

**Comment by csukuangfj** [comment]
Also, the process gets stuck until I process `ctrl + C` to kill it:
Screen Shot 2022-10-10 at 10 53 24


Screen Shot 2022-10-10 at 10 53 41

**Comment by pzelasko** [comment]
I see. When calling `.filter()`, you would have to change the lambda into a function or `pip install dill` to allow pickling lambdas (lhotse auto-magically supports this); there is no other way if you want to keep the manifest lazy, because it's using a lambda in `.filter` and attempting to pass it to subprocesses, so it must be pickled.

**Comment by csukuangfj** [comment]
Thanks!

```
pip install dill
```

works perfectly. 

I don't use `pip install` to install lhotse so I did not have `dill` in my environment. After installing `dill` manually, everything works fine.

**Review by csukuangfj — APPROVED** [review]

**Comment by pzelasko** [comment]
@csukuangfj `dill` is an optional dependency for Lhotse, as I am trying to limit the scope the amount of core dependencies as much as possible. That means unless it becomes a core dependency of Icefall, the users will run into the same issue as you with hanging training due to lambda. If the solution in this PR is acceptable, then I suggest to add `dill` to Icefall requirements.

**Comment by csukuangfj** [comment]
> @csukuangfj `dill` is an optional dependency for Lhotse, as I am trying to limit the scope the amount of core dependencies as much as possible. That means unless it becomes a core dependency of Icefall, the users will run into the same issue as you with hanging training due to lambda. If the solution in this PR is acceptable, then I suggest to add `dill` to Icefall requirements.

Thanks! Added in https://github.com/k2-fsa/icefall/pull/613

**Pull request merged**
