### PR TITLE
Add recipe for the yes_no dataset.

### PR DESCRIPTION
**Pull request by csukuangfj**

### CODE REVIEW

**Comment by csukuangfj** [comment]
See https://github.com/k2-fsa/icefall/pull/16

**Comment by pzelasko** [comment]
Thanks! Could you add an entry in the corpora list in `docs/corpus.rst`?

**Comment by csukuangfj** [comment]
> Thanks! Could you add an entry in the corpora list in `docs/corpus.rst`?

Ok. Just added an entry to it and fixed several typos.

**Comment by pzelasko** [comment]
> Ok. Just added an entry to it and fixed several typos.

Nice, thanks! BTW are you adopting black for k2? I might reformat whole Lhotse codebase with it at some point…

**Comment by csukuangfj** [comment]
> > Ok. Just added an entry to it and fixed several typos.
> 
> Nice, thanks! BTW are you adopting black for k2? I might reformat whole Lhotse codebase with it at some point…

I am using black for icefall, but yapf for k2.
Maybe we should also use black to reformat the files in k2 at some point.

**Pull request merged**
