### PR TITLE
Support multi-channel wavs in Kaldi export

### PR DESCRIPTION
**Pull request by pzelasko**

### CODE REVIEW

**Comment by jtrmal** [comment]
LGTM

**Comment by jtrmal** [comment]
btw, one thing why I left it there was I wasn't sure about enforcing/supporting the audio sampling freq (which was why the ffmpeg filter includes/included the frame rate conversion stuff

**Comment by pzelasko** [comment]
Gotcha. I'm waiting for Ashish to tell me if this fixes his CHiME6 Lhotse+Kaldi setup, will merge soon after.

**Comment by aarora8** [comment]
Hi Thanks!. It is working well for me.

**Pull request merged**
