### PR TITLE
Test for wav augment + parallel executor

### PR DESCRIPTION
**Pull request by pzelasko**

### CODE REVIEW

**Comment by pzelasko** [comment]
@freewym can you check if this test runs alright for you? I tested both on my laptop and the CLSP grid, and there seems to be no issue.

**Comment by freewym** [comment]
It's alright for me

**Comment by pzelasko** [comment]
Ok. How can I reproduce issue #121 ?

**Comment by freewym** [comment]
https://github.com/freewym/espresso/pull/45/files

checkout this PR; install  Espresso as in README;  `make lhotse`;  run `run.sh`

**Comment by freewym** [comment]
The issue is gone if lambda expressions are replaced by functions (e.g, replace 
 lambda at this line https://github.com/freewym/espresso/pull/45/files#diff-3724bd15a663fd58b5fc92daa096bc9eb0c0a96a4c070a1a9e999be0682c985aR319 with `_get_factor()`, and `_get_factor()' should be defined outside of `speed()`)

I don't know why this matters...

**Comment by danpovey** [comment]
How did you figure that out?

**Comment by freewym** [comment]
Well, just gradually change from a working example to the problematic one...

**Comment by pzelasko** [comment]
AFAIK It's related to how Python does multi processing. It forks the main
process and sends all data via pickles. Lambdas with captures are not
pickle-able, but functions are (don't ask me why...) although I would have
expected it to crash rather than hang.

pon., 9 lis 2020, 23:59 użytkownik Yiming Wang <notifications@github.com>
napisał:

**Comment by pzelasko** [comment]
Oh damn now this test is hanging in the CI. When I have some more time again I will just add support for torchaudio, I'm tired of working around WavAugment quirks...

**Comment by mthrok** [comment]
Let me know if you need help for `torchaudio`.

Note that `torchaudio` also has a similar edge case where transform implemented in C++ hangs. It only happens on macOS, Python 3.6/3.7 and when the function is called in subprocess. It's being tracked here.
https://github.com/pytorch/pytorch/issues/46409

**Comment by pzelasko** [comment]
ooh la la... thanks for letting us know. That libsox turns out to be quite naughty...

**Pull request merged**
